name: jfnkl
favicon: null
layout_spectrum: 0.6222364497371018
typography_spectrum: 0.9932993864640594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6c5d5a'
    - '#f2f2f2'
    - '#bab5b2'
    - '#0a0605'
    - '#897f7e'
  brandStrength: 0.49098896770738065
  lightness: 0.992065295111388
  saturation: 0.86966254375875
  rhythmicContrast: 0.75
purpose: []
